<h1>Aide en ligne</h1>
<div class="tit_bot">
	<div class="right_b_aide"><span class="col_b"></span><br />
		<?php
		//Affichage de l'aide
		$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
		$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
		
		//Ca c'est du scotch et des agraffes
		if($controllerName == "index")
			$controllerName = "Index";
		
		//echo $controllerName."</br>".$actionName;
		
		$dom = new DomDocument;
		$dom->load(APPLICATION_PATH."/configs/aide.xml");
		$AideControllerItem = $dom->getElementsByTagName($controllerName)->item(0);
		$Aide = $AideControllerItem->getElementsByTagName($actionName)->item(0)->firstChild->nodeValue;
		
		echo $Aide;
	
	?>
	</div>
 </div>
 <h2></h2>
 <br />