<?php

	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('CRC');
	
	echo $this->doctype(); ?>
	<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
		<head>
			<?php echo $this->headMeta(); ?>
			<?php echo $this->headTitle(); ?>
			<?php 
				echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); 
			?>	
			<?php
					$this->jQuery()->enable();
					$this->jQuery()->addStylesheet("http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css");
					$this->jQuery()->addStylesheet("http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/ui-lightness/jquery-ui.css"); 
					echo $this->jQuery();
			?>
		</head>
		<body>
			
			<div id="wrapper">
				<div id="header">
					<div id="logo">
						<h1><a href="#">crc </a></h1>
						<p>Caisse de retraite complémentaire</p>
					</div>
					<div id="authsearch">
						<div id="authentification">
							<?php echo $this->login();  ?>
						</div>
						<div id="search">
							<form method="get" action="">
								<fieldset>
									<input type="text" name="s" id="search-text" size="15" value="enter keywords here..." />
									<input type="submit" id="search-submit" value="GO" />
								</fieldset>
							</form>
						</div>
					</div>
				</div>
				<!-- end #header -->
				<div id="page">
					<div id="page-bgtop">
						<div id="page-bgbtm">
							<div id="menu">
								<ul>
								<?php
									$auth=Zend_Auth::getInstance();
									if(!$auth->hasIdentity()){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Demande','action'=>'affiliation'));?>">S'affilier</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
								}
								else{
									$profil = $auth->getIdentity();
									$droits = $profil->Droits;
									if($droits==0){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index','id'=>$profil->Id_utilisateur));?>">Voir mon profil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Demande','action'=>'index'));?>">Déposer une demande</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
									}
									if($droits==1){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index','id'=>$profil->Id_utilisateur));?>">Voir mon profil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
									}
									if($droits==2){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index','id'=>$profil->Id_utilisateur));?>">Voir mon profil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'dads'));?>">Envoyer la DADS</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
									}
									if($droits==3){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index','id'=>$profil->Id_utilisateur));?>">Voir mon profil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Liste-demandes','action'=>'index'));?>">Liste des demandes</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Recherche','action'=>'liste-adherents'));?>">Liste des adhérents</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
									}
									if($droits==4){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index','id'=>$profil->Id_utilisateur));?>">Voir mon profil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Transfer','action'=>'dossier'));?>">Transférer dossier</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
									}
									if($droits==5){
								?>
								<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index','id'=>$profil->Id_utilisateur));?>">Voir mon profil</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Transfert','action'=>'autorisation-depart'));?>">Envoyer autorisations de départ</a></li>
								<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								<?php
								}}
								?>							
								</ul>
									
							</div>
							<!-- end #menu -->
							<div id="content">
								<div class="post">
									<h2 class="title"><?php echo $this->escape($this->title); ?></h2>
									
									<div class="entry">
										<?php echo $this->layout()->content; ?>
									</div>
									
								</div>
								
								<div style="clear: both;">&nbsp;</div>
								
							</div>
							<!-- end #content -->
							<div id="sidebar">
								<div id="auth">
									
									
									
								</div>
								<ul>
									<li>
										<h2>Aide</h2>
										Ici un élément du Layout nommé 'aide'
										A remplir en fonction du contexte
										<?php echo $this->layout()->aide; ?>
									</li>
								</ul>
							</div>
							<!-- end #sidebar -->
							<div style="clear: both;">&nbsp;</div>
						</div>
					</div>
				</div>
				<!-- end #page -->
			</div>
			<div id="footer-wrapper">
				<div id="footer">
					<p>Copyright (c) 2011</p>
				</div>
			</div>	
		</body>
	</html>