<h2>Recherche par entreprises : </h2>

<?php
echo $this->form;
?>

<h2>Résultats de la recherche :</h2>


<?php
if(sizeof($this->listeEntreprises) <= 0)
	{
		echo "Aucun enregistrement trouvé.";
	}
else
	{
?>
		<table <?php echo "id='afficher_ent'"; ?>>
			<thead>
				<tr>
					<th>ID</th>
					<th>Siret</th>
					<th>Nom</th>
					<th>Adresse</th>
					<th>Email</th>
					<th>Téléphone</th>
				</tr>
			</thead>

<?php
		foreach($this->listeEntreprises as $entreprise) : 
?>
			<tbody>
				<tr>
					<td><?php echo $this->escape($entreprise->Id_utilisateur);?></td>
					<td><?php echo $this->escape($entreprise->Num_siret);?></td>
					<td><?php echo $this->escape($entreprise->Nom_entreprise);?></td>
					<td><?php echo $this->escape($entreprise->Adresse);?></td>
					<td><?php echo $this->escape($entreprise->Num_tel);?></td>
					<td><?php echo $this->escape($entreprise->E_mail);?></td>
				</tr>
			</tbody>
		</table>	
<?php
		endforeach; 
	}
?>


<script type="text/javascript"> 
$(function () {
	tableToGrid("#afficher_ent", {width: "650" ,height: "auto", caption: "Résultats de la recherche :"});
});

$(function () {
		$("#afficher_ent").jqGrid('gridResize',{minWidth:650,maxWidth:1000,minHeight:100, maxHeight:800});
	});


</script>