<h3>Périodes</h3>

	<table id='periode'>
	<thead>
		<tr>
			<th>Entreprise</th>
			<th>Salaire</th>
			<th>Point ARRCO</th>
			<th>Point AGIRC</th>
			<th>Documents liés</th>
		</tr>
	</thead>
	<tbody>
	<?php 
		$i=0;
		foreach($this->Periodes as $periode) : ?>
		<tr>
			<td><?php echo $this->escape($periode->Nom_Entreprise);?></td>
			<td><?php echo $this->escape($periode->Salaire_percu);?></td>
			<td><?php echo $this->escape($periode->Points_ARRCO);?></td>
			<td><?php echo $this->escape($periode->Points_AGIRC);?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'Document','action'=>'afficher-Documents', 'id_periode'=>$periode->Id_periode));?>">Voir</a></td>
		</tr>
		<?php 
			$i++;
			endforeach; ?>
		</tbody>
	
	</table>
	
<br />

<script>
		$(function () {
			tableToGrid("#periode", {height:'auto',caption: 'Période du <?php $datedeb = explode(" ",$this->escape($periode->Date_debut)); 
					  echo trim($datedeb[0]);?> au <?php $datefin = explode(" ",$this->escape($periode->Date_fin)); 
					  echo trim($datefin[0]);?>'});;
		});
</script>
	

