<h2>Création de l'entreprise</h2>

<table id="afficher_ent">
	<thead>
		<tr>
			<th>ID</th>
			<th>Siret</th>
			<th>Nom</th>
			<th>Adresse</th>
			<th>Email</th>
			<th>Téléphone</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><?php echo $this->escape($this->afficherEntreprise["Id_utilisateur"]);?></td>
			<td><?php echo $this->escape($this->afficherEntreprise["Num_siret"]);?></td>
			<td><?php echo $this->escape($this->afficherEntreprise["Nom_entreprise"]);?></td>
			<td><?php echo $this->escape($this->afficherEntreprise["Adresse"]);?></td>
			<td><?php echo $this->escape($this->afficherEntreprise["Num_tel"]);?></td>
			<td><?php echo $this->escape($this->afficherEntreprise["E_mail"]);?></td>
		</tr>
	</tbody>
</table>	

<script type="text/javascript"> 
$(function () {
	tableToGrid("#afficher_ent", {width: "650" ,height: "auto", caption: "Informations générales :"});
});

$(function () {
		$("#afficher_ent").jqGrid('gridResize',{minWidth:650,maxWidth:1000,minHeight:100, maxHeight:800});
	});


</script>