<?php 
		//on cherche l'instance de connexion
		$auth=Zend_Auth::getInstance();
		//on récupère son niveau de droit
		//pour chaque niveau on définit l'affichage du menu / restriction d'acccès aux actions/vues
		$profil = $auth->getIdentity();
		$droits = $profil->Droits;
		
		?>

<script type="text/javascript"> 
$(function() {
	$( "#tabs" ).tabs();
});

</script>
<p class="news_intro">
		Bienvenue dans la section Profil :
</p>
<p class="news_content">
	Vous trouverez ici l'ensemble des informations concernant votre dossier, vous avez ainsi la possibilité de les modifier.
	<?php 
		if($droits !=3 || ($droits != $this->droit_profil && $droits == 3)){
	?> 
	<br><br>Vous trouverez dans l'onglet 'Vos demandes' la liste des demandes que vous avez effectué auprès de nos services.
	<?php if($droits == 0 || $droits == 1 || ($droits != $this->droit_profil && $droits == 3)){ ?>
	<br><br>L'onglet 'Votre carrière' réuni l'ensemble des informations relatives à votre carrière détaillée par période ainsi que l'ensemble des documents justificatif que vous nous avez fournis.
	<?php }	}?>
</p>

	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">Vos informations</a></li>
			<?php 
				if($droits !=3 || ($droits != $this->droit_profil && $droits == 3)){
			?>
			<li><a href="#tabs-2">Vos RIB</a></li>
			<li><a href="#tabs-3">Vos demandes</a></li>
			<?php if($droits == 0 || $droits == 1 || ($droits != $this->droit_profil && $droits == 3 && ($this->droit_profil == 0 || $this->droit_profil == 1))){ ?>
		
			<li><a href="#tabs-4">Votre carrière</a></li>
			<?php }	}?>
			
			<?php 
				if(($droits != $this->droit_profil && $droits == 3 && ($this->droit_profil == 0 || $this->droit_profil == 1)) || $droits == 1 || $droits == 0) {
			?>
			<li><a href="#tabs-5">Droits</a></li>
			<?php }
			if(($droits != $this->droit_profil && $droits == 3 && ($this->droit_profil == 0 || $this->droit_profil == 1)) || $droits == 1){
			?>
			<li><a href="#tabs-6">Plan de retraite</a></li>
			<?php }	?>
		</ul>
		
		<div id='tabs-1' >
				<?php 
					$this->title = "Mon Profil";
					$this->headTitle($this->title);
					echo $this->form;
				?>
		
		</div>
		<?php 
				if($droits !=3 || ($droits != $this->droit_profil && $droits == 3)){
			?>
		<div id='tabs-2' >
			
				<?php 
					//On affiche les demandes de l'utilisateur
					echo $this->action('afficher-rib', 'rib', null, array('id' => ($this->id))); 
				?>
			
		</div>
		<div id='tabs-3' >
			
				<?php 
					//On affiche les demandes de l'utilisateur
					echo $this->action('index', 'ListeDemandes', null, array('id' => ($this->id))); 
				?>
			
		</div>
		<?php if($droits == 0 || $droits == 1 || ($droits != $this->droit_profil && $droits == 3 && ($this->droit_profil == 0 || $this->droit_profil == 1))){ ?>
		
		<div id='tabs-4' >
				<?php 
					//On affiche la carrière de l'adhérent
					echo $this->action('afficher-Carriere', 'Carriere', null, array('id' => ($this->id))); 
				?>
		</div>
		<?php }	}?>
		<?php 
				if(($droits != $this->droit_profil && $droits == 3 && ($this->droit_profil == 0 || $this->droit_profil == 1)) || $droits == 1 || $droits == 0){
			?>
		<div id='tabs-5'>
			<?php 
					//On affiche le droit à la retraite de l'adhérent
					echo $this->action('afficher-Droit', 'Carriere', null, array('id' => ($this->id)));
				 
			?>
		</div>
		<?php } if(($droits != $this->droit_profil && $droits == 3 && ($this->droit_profil == 0 || $this->droit_profil == 1)) || $droits == 1){?>
		<div id='tabs-6'>
			<?php 
					//On affiche le plan de retraite de l'adhérent
					echo $this->action('afficher-Plan', 'Carriere', null, array('id' => ($this->id))); 
			?>
		</div>
		<?php }	?>
		
	</div>
