<table id='afficher_demande' border="1">
	<thead>
		<tr>
			<th>ID</th>
			<th>Numéro de courrier</th>
			<th>Déposé par</th>
			<th>Date</th>
			<th>Etat</th>
			<th>Type</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><?php echo $this->escape($this->afficher_demande->Id_demande);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Id_courrier);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Id_utilisateur);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Date_demande);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Etat);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Type);?></td>
		</tr>
	</tbody>
</table>

<br />

<table id='afficher_demande_commentaire' >
	<thead>
		<tr>
			<th>Commentaire sur la demande</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><?php echo $this->escape($this->afficher_demande->Commentaires);?></td>
		</tr>
	</tbody>	
</table>
	
	

<script>
	$(function () {
		tableToGrid("#afficher_demande", {height:"auto", caption: "Informations sur la demande"});
		tableToGrid("#afficher_demande_commentaire", {height:"auto"});
	});
</script>