
<table id='listedemandes' class='tableclass'>
	<thead>
		<tr>
			<td>ID</td>
			<td>Numéro de courrier</td>
			<td>Déposé par</td>
			<td>Date</td>
			<td>Etat</td>
			<td>Type</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><?php echo $this->escape($this->afficher_demande->Id_demande);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Id_courrier);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Id_utilisateur);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Date_demande);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Etat);?></td>
			<td><?php echo $this->escape($this->afficher_demande->Type);?></td>
		</tr>
	</tbody>
	<tfoot></tfoot>
</table>

<br />

<table id='listedemandes' class='tableclass'>
		<thead>
			<tr>
				<td>Commentaire</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->afficher_demande->Commentaires);?></td>
			</tr>
		</tbody>
		<tfoot></tfoot>
	</table>
	