<h2>Notes</h2>

<?php 

$i=0;

foreach($this->afficherNote as $demande) : ?>
	<table <?php echo "id='afficher_note_$i'"; ?>>
		<tr>
			<th>Posté par <?php echo $this->escape($demande->Id_utilisateur)." le ".$this->escape($demande->Date_soumission);?></th>
		</tr>
		<tr>
			<td><?php echo $this->escape($demande->Contenu);?></td>
		</tr>
	</table>
<br />

<script>
		$(function () {
			tableToGrid("#afficher_note_<?php echo $i ?>", {height:'100'});;
		});
</script>
	

<?php 
$i++;

endforeach; ?>

