<h2>Notes</h2>

<?php 

$i=0;

foreach($this->afficherNote as $demande) : ?>
	<table <?php echo "id='afficher_note_$i'"; ?>>
		<tr>
			<th>#<?php echo $this->escape($demande->Id_note)?></th>
		</tr>
		<tr>
			<td><?php echo $this->escape($demande->Contenu);?></td>
		</tr>
	</table>
<br />

<script>
		$(function () {
			tableToGrid("#afficher_note_<?php echo $i ?>", {height: "auto", caption: "<?php echo "Posté par ".$this->escape($demande->Login)." le ".$this->escape($demande->Date_soumission);?>"});
		});
</script>


<?php
$i++;

endforeach; ?>

