<?php
	$this->title = 'Listes des demandes';
	$this->headTitle($this->title);
?>

	<table id='listedemandes'>
		<thead>
			<tr>
				<th>ID</th>
				<th>Type de demande</th>
				<th>Date de demande</th>
				<th>Etat</th>
				<th>Demandeur</th>
				<th>Voir</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->demandes as $demande) : 
			if(!isset($this->id) || (isset($this->id) && $this->id == $demande->Id_utilisateur)){?>
			<tr>
				<td><?php echo $this->escape($demande->Id_demande);?></td>
				<td><?php echo $this->escape($demande->Type);?></td>
				<td>
				<?php
					$date = explode(" ",$this->escape($demande->Date_demande)); 
					echo $date[0];
				?>
				</td>
				<td>
				<?php $etat = $this->escape($demande->Etat);
						  if($etat == 0){
						  	echo "En attente";
						  }elseif ($etat == 1){
						  	echo "En cours";
						  }else {
						  	echo "Traité";
						  }
				?>
				</td>
				<td>
					<?php
						$utilisateur = new Application_Model_DbTable_Utilisateur();
						if($utilisateur->exist($demande->Id_utilisateur)){
						
					?>
					<a href="<?php echo $this->url(array('controller'=>'Profil','action'=>'index', 'id'=>$demande->Id_utilisateur));?>">Voir</a>
					<?php } ?>
					
				</td>
				<td>
				<?php
					$type = $this->escape($demande->Type);
					
					  if($type == "demande affiliation")
						{
				?>
							<a href="<?php echo $this->url(array('controller'=>'AfficherLesDemandes',
								'action'=>'demande-affiliation', 'id'=>$demande->Id_demande));?>">Voir</a>
				<?php
						}
					  else if($type == "demande informations")
						{
				?>
							<a href="<?php echo $this->url(array('controller'=>'AfficherLesDemandes',
								'action'=>'demande-informations', 'id'=>$demande->Id_demande));?>">Voir</a>
				<?php
						}
				?>
					
				</td>
			</tr>
			<?php 
			}
			endforeach; ?>
		</tbody>
	</table>

<script>
	$(function () {
		//tableToGrid("#listedemandes", {width:'auto',height:'auto'});
	});
</script>