<br /><br />
<div id="view-content">
	<p>View script for controller <b>ListeDemandes</b> and script/action name <b>index</b></p>
	<table id='listedemandes' class='tableclass'>
		<thead>
			<tr>
				<td>ID</td>
				<td>Type de demande</td>
				<td>Date de demande</td>
				<td>Etat</td>
				<td>Demandeur</td>
				<td>Voir</td>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->demandes as $demande) : ?>
			<tr>
				<td><?php echo $this->escape($demande->Num_demande);?></td>
				<td><?php echo $this->escape($demande->Type);?></td>
				<td><?php echo $this->escape($demande->Date_demande);?></td>
				<td>
					<a href="<?php echo $this->url(array('controller'=>'Profil',
					'action'=>'infosPerso', 'id'=>$demande->Adh_Identifiant));?>">Voir</a>
				</td>
				<td>
					<a href="<?php echo $this->url(array('controller'=>'ListeDemandes',
					'action'=>'index', 'id'=>$demande->id));?>">Voir</a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
		<tfoot></tfoot>
	</table>
</div>