<?php

	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('CRC');
	
	echo $this->doctype(); ?>
	<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
		<head>
			<?php echo $this->headMeta(); ?>
			<?php echo $this->headTitle(); ?>
			<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>	
		</head>
		<body>
			
			<div id="wrapper">
				<div id="header">
					<div id="logo">
						<h1><a href="#">crc </a></h1>
						<p>Caisse de retraite complémentaire</p>
					</div>
					<div id="authsearch">
						<div id="authentification">
							<?php echo $this->login();  ?>
						</div>
						<div id="search">
							<form method="get" action="">
								<fieldset>
									<input type="text" name="s" id="search-text" size="15" value="enter keywords here..." />
									<input type="submit" id="search-submit" value="GO" />
								</fieldset>
							</form>
						</div>
					</div>
				</div>
				<!-- end #header -->
				<div id="page">
					<div id="page-bgtop">
						<div id="page-bgbtm">
							<div id="menu">
								<ul>
									<li class="current_page_item"><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">Accueil</a></li>
									<li><a href="#">Voir mon profil</a></li>
									<li><a href="<?php echo $this->url(array('controller'=>'Demande','action'=>'index'));?>">Déposer une demande</a></li>
									<li><a href="#">Envoyer la DADS</a></li>
									<li><a href="#">Envoyer autorisations de départ</a></li>
									<li><a href="#">Transférer dossier</a></li>
									<li><a href="#">Afficher la liste des demandes</a></li>
									<li><a href="#">Afficher la liste des adhérents</a></li>
									<li><a href="#">S'affilier</a></li>
									<li><a href="<?php echo $this->url(array('controller'=>'Contact','action'=>'index'));?>">Contact</a></li>
								</ul>
							</div>
							<!-- end #menu -->
							<div id="content">
								<div class="post">
									<h2 class="title"><?php echo $this->escape($this->title); ?></h2>
									
									<div class="entry">
										<?php echo $this->layout()->content; ?>
									</div>
									
								</div>
								
								<div style="clear: both;">&nbsp;</div>
								
							</div>
							<!-- end #content -->
							<div id="sidebar">
								<div id="auth">
									
									
									
								</div>
								<ul>
									<li>
										<h2>Aide</h2>
										Ici un élément du Layout nommé 'aide'
										A remplir en fonction du contexte
										<?php echo $this->layout()->aide; ?>
									</li>
								</ul>
							</div>
							<!-- end #sidebar -->
							<div style="clear: both;">&nbsp;</div>
						</div>
					</div>
				</div>
				<!-- end #page -->
			</div>
			<div id="footer-wrapper">
				<div id="footer">
					<p>Copyright (c) 2011</p>
				</div>
			</div>	
		</body>
	</html>