<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
	<head>
		<?php
			echo $this->headMeta(); 
			echo $this->headTitle();
			$this->headTitle()->setSeparator(' - ');
			$this->headTitle('CRC');

			//CSS
			$this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); 
			$this->headLink()->prependStylesheet($this->baseUrl().'/css/cadre.css'); 
			$this->headLink()->prependStylesheet($this->baseUrl().'/css/carousel.css'); 
			$this->headLink()->prependStylesheet($this->baseUrl().'/css/ui.jqgrid.css'); 
			$this->headLink()->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.12.custom.css'); 
			
			//jQuery
			$this->jQuery()->enable();
				
			//JS
			$this->headScript()->appendFile($this->baseUrl().'/js/JQueryCarousel/ie6.js');
			$this->headScript()->appendFile($this->baseUrl().'/js/JQueryCarousel/carousel.js');
			$this->headScript()->appendFile($this->baseUrl().'/js/Jqgrid/i18n/grid.locale-fr.js');
			$this->headScript()->appendFile($this->baseUrl().'/js/Jqgrid/jquery.jqGrid.min.js');
			$this->headScript()->appendFile($this->baseUrl().'/js/Jquery/js/jquery-ui-1.8.13.custom.min.js');
			
			//appel des librairies / affichage
			echo $this->headLink();	
			echo $this->jQuery();	
			echo $this->headScript();	

		?>
	</head>
	<body style="text-align: center; width:width: 1016px;">
		<div id="main">
			<!-- HEADER -->
			<!-- MENU + CAROUSEL -->
			<?php echo $this->render('header.phtml') ?>
			<!-- END GEADER -->
			
			<!-- CONTENT -->
			<div id="content">
				<div class="top">
					<!-- MENU ON RIGHT -->
					<div id="right">
						<!-- MODULE CONNEXION -->
						<?php echo $this->render('connexion.phtml') ?>
						<!-- MODULE AIDE -->
						<?php echo $this->render('aide.phtml') ?>
					</div>  
					<!-- END MENU ON RIGHT -->
					<!-- MAIN PAGE -->
					<div id="left">
						<?php echo $this->render('content.phtml') ?>
					</div>
					<!-- END MAIN PAGE -->
					<br />
					<div style="clear: both"></div>
				</div>
				<div class="bot"></div>
			</div>
			<!-- END CONTENT -->
 
		<!-- FOOTER -->
		<?php echo $this->render('footer.phtml') ?>
		<!-- END FOOTER -->
		</div>
	</body>
</html>
