
<?php
$this->title = "La retraite en toute simplicité";
$this->headTitle($this->title);
?>
<p class="news_intro">
	Vous souhaitez demander votre départ en retraite? Rien de plus facile:

</p>
<p class="news_content">
	Il vous suffit de remplir ce formulaire. Pour plus de commodité et de simplicité à l'égard de nos adhérents, nous avons simplifié au maximum les démarches de départ en retraite.
	Nous nous chargeons de tout pour vous, vous n'avez qu'à nous spécifier la date souhaité de départ.

	La démarche :
	<ul>
		<li>Remplissez ce formulaire et effectuez votre demande</li>
		<li>Nos services étudieront celle-ci sous 36 jours maximum</li>
		<li>Si vos droits vous le permette, un plan de liquidation de retraite vous sera proposé</li>
		<li>Vous pourrez ainsi profiter de votre retraite en toute sérénité</li>
	</ul>	
</p>
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Votre demande</a></li>
		<li><a href="#tabs-2">Conditions de validité</a></li>
		<li><a href="#tabs-3">Renseignements</a></li>
	</ul>
	<div id="tabs-1">
		<?php
			echo $this->form;
		?>
	</div>
	<div id="tabs-2">
	<h2>Le régime général:</h2>

	<h3>L'âge légal</h3>
	<p class="news_content">Pour le régime général (celui des salariés), l'âge légal de départ en retraite est fixé à 60 ans. Pour bénéficier d'une retraite à taux plein, une personne doit totaliser 160 trimestres de cotisation. A partir de 65 ans, la retraite à taux plein est accordée sans condition.

	Cependant le taux plein de 50% est automatiquement accordé avant 65 ans même si le nombre de trimestres acquis est inférieur à 160, pour les cas suivants :<br>
	<ul>
	<li>les personnes ayant commencé à travailler avant 16 ou 17 ans et justifiant d'une carrière longue (à partir de 56 ans)</li>
	<li>les travailleurs handicapés (à partir de 55 ans)</li>
	<li>les personnes inaptes au travail (à partir de 60 ans)</li>
	<li>les bénéficiaires d'une pension d'invalidité (à partir de 60 ans)</li>
	<li>les anciens combattants, prisonniers de guerre, déportés ou internés politique ou de la résistance, mères ouvrières… (à partir de 60 ans)</li>
	</ul>
	</p>
	<h3>L'augmentation de la durée de cotisation</h3>
	<p class="news_content">
	Pour les salariés atteignant 60 ans entre 2009 et 2012, le nombre d'années de cotisations augmentera à raison d'un trimestre par an et par année de naissance pour atteindre 164 trimestres.
	A compter de 2012, il évoluera en fonction de l'espérance de vie.
	A partir de 60 ans, s'il vous manque des trimestres pour valider votre retraite, vous pouvez demander votre retraite, qui dans ce cas sera calculée à partir d'un taux minoré.
	</p>
	<h3>La retraite complémentaire</h3>
	<p class="news_content">
	La retraite complémentaire est accordée sans minoration à partir de 65 ans sous seule condition d'avoir cessé toute activité professionnelle, mais également avant 65 ans si vous bénéficier de la retraite de base de la sécurité sociale à taux plein.
 	</p>
 	<h3>La préretraite</h3>
	<p class="news_content">Pour les salariés ne bénéficiant pas d'un régime spécifique, il est possible de partir en préretraite à partir de 50 ans, selon le type de préretraite qui peut lui être accordé.
	Le départ en préretraite est soumis à condition et n'est pas accessible à tous les salariés, il dépend essentiellement de la profession exercée mais aussi de l'entreprise.
	<br>
	Dans le cadre d'une préretraite engagée pour éviter un licenciement, le salarié doit avoir au moins 57 ans. Mais pour qu'un départ en préretraite licenciement soit envisagé, il faut que le salarié ait adhéré à une convention ASFNE, préalablement conclue entre l'entreprise et l'Etat. Pour une préretraite métiers difficiles, le demandeur doit avoir adhéré au dispositif entre 55 et 65 ans mais également avoir accompli un travail pénible pendant 15 ans. La préretraite amiante est elle, réservée aux 50 ans et plus qui ont travaillé dans l'amiante.
	Il est également possible de bénéficier d'une préretraite entreprise qui dépend essentiellement de l'ancienneté au sein de l'entreprise.
 	</p>
 	<br>
 	<h2>Le régime des artisans, commerçants, professions libérales et exploitants agricoles:</h2>
	<p class="news_content">
	L'âge de départ en retraite pour les régimes des artisans ou commerçants, des professions libérales, des exploitants agricoles suit les mêmes règles que le régime général.
 	</p>
 	<br>
 	<h2>Le régime des fonctionnaires:</h2>

	<h3>L'âge légal</h3>
	<p class="news_content">
	Les fonctionnaires bénéficient de conditions d'âge différentes pour le départ en retraite. Pour bénéficier d'une pension de retraite, ils doivent au préalable être radiés des cadres. Les fonctionnaires civils peuvent demander leur retraite au bout de 15 ans de service effectif.
	Pour les fonctionnaires remplissant une condition d'âge, l'âge de départ en retraite est de 60 ans dans le cas général et 55 ans pour ceux qui ont accompli 15 années de service dans un emploi classé dans la catégorie active.
	Pour certains emplois, tels que les instituteurs, l'âge de retraite est rabaissé à 55 ans et pour les professions telles que policiers ou gardiens de prison, le départ en retraite est possible à partir de 50 ans.
	Les fonctionnaires sont mis à la retraite d'office à 65 ans dans le cadre général ou à 60 ans s'ils ont effectué un emploi classé dans la catégorie active.
 	</p>
 	<br>
 	<h3>Le départ anticipé</h3>
	<p class="news_content">
	Le départ en retraite anticipé est possible à tout âge et sans condition de durée :
	<ul>
		<li>si vous êtes radié des cadres pour invalidité.</li>
		<li>après 15 ans de service, si vous ou votre conjoint êtes reconnus inaptes à l'exercice d'une profession quelconque.</li>
		<li>après 15 ans de service et sous certaines conditions : si vous êtes père ou mère d'au moins 3 enfants, ou si vous avez élevé des enfants pendant au moins 9 ans, ou si vous avez un enfant de plus d'un an atteint d'une invalidité au moins égale à 80%.</li>
		<li>avant 60 ans au titre d'une carrière longue.</li>
 	</ul>
	<h2>Les régimes spéciaux:</h2>
	<p class="news_content">
	L'âge de départ en retraite est différent également pour les régimes spéciaux, ainsi on notera qu'un agent de conduite de la SNCF peut partir en retraite à 50 ans après 25 ans de service.
	</p>
	</div>
	<div id="tabs-3">
	<h3>Une question?</h3>
	Pour toute question concernant votre dossier ou la législation en vigueur vous pouvez nous adresser une <a href="<?php echo $this->url(array('controller'=>'demande','action'=>'informations'));?>">demande d'informations</a>.<br>
	Elle sera traité dans les plus brefs délais par nos services.
	</div>
</div>
<script type="text/javascript"> 
$(function() {
	$( "#tabs" ).tabs();
});

</script>