<?php
	$this->title = 'Fiche demande affiliation';
	$this->headTitle($this->title);
?>
<div id="view-content">

<?php echo $this->action('demande', 'AfficherLesDemandes', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); ?>

	<table id='listedemandes' class='tableclass'>
		<thead>
			<tr>
				<td>Raison sociale</td>
				<td>numéro de SIRET</td>
				<td>Mail</td>
				<td>Adresse</td>
				<td>Téléphone</td>
				<td>Nombre employés</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Nom);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Num_siret);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Telephone);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Nombre_employes);?></td>
			</tr>
		</tbody>
		<tfoot></tfoot>
	</table>
</div>