<?php
	$this->title = 'Fiche demande affiliation';
	$this->headTitle($this->title);
?>
<div id="view-content">


<?php 

	//appel de l'action demande du controller AfficherLesDemandes
	echo $this->action('demande', 'AfficherLesDemandes', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 
?>

	<table id='listedemandes_affiliation_1' >
		<thead>
			<tr>
				<th>Raison sociale</th>
				<th>numéro de SIRET</th>
				<th>Nombre employés</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Nom);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Num_siret);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Nombre_employes);?></td>
			</tr>
		</tbody>
	</table>
	
	<table id='listedemandes_affiliation_2' >
		<thead>
			<tr>
				<th>Mail</th>
				<th>Adresse</th>
				<th>Téléphone</th>
				</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->E_mail);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Adresse);?></td>
				<td><?php echo $this->escape("0".$this->afficher_demande_affiliation->Telephone);?></td>
				
			</tr>
		</tbody>
	</table>
	
	<script>
		$(function () {
			tableToGrid("#listedemandes_affiliation_1", {height:"auto", caption: "Informations sur l'entreprise"});
			tableToGrid("#listedemandes_affiliation_2", {height:"auto", caption: "Coordonnées de l'entreprise"});
		});
	</script>
	
	<?php 

	//lister les notes de cette demande et les afficher
	echo $this->action('afficher-notes', 'Note', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 

	//afficher la liste des documents
	echo $this->action('afficher-documents', 'Document', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 
	
	//appel de l'action demande du controller AfficherLesDemandes
	//formulaire pour ajouter une note
	echo $this->action('ajouter-note', 'Note', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 
	
	//on ajoute un document
	echo $this->action('ajouter-document', 'Document', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 
	?>
	
	</div>



