<?php
	$this->title = 'Fiche demande affiliation';
	$this->headTitle($this->title);
?>
<div id="view-content">


<?php 

	//appel de l'action demande du controller AfficherLesDemandes
	echo $this->action('demande', 'AfficherLesDemandes', null, array('id' => ($this->afficher_demande_affiliation->Id_demande), 'prov' => (md5("demandeAffiliation")))); 
	
?>

	<table id='listedemandes_affiliation_1' >
		<thead>
			<tr>
				<th>ID</th>
				<th>Raison sociale</th>
				<th>numéro de SIRET</th>
				<th>Nombre employés</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php
				if(isset($this->entrepriseExiste->Nom_entreprise))
					{
						echo "<td>".$this->entrepriseExiste->Id_utilisateur."</td>";
					}
				else
					{
						echo "<td>NULL</td>";
					}
				?>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Nom);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Num_siret);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Nombre_employes);?></td>
			</tr>
		</tbody>
	</table>
	
	<table id='listedemandes_affiliation_2' >
		<thead>
			<tr>
				<th>Mail</th>
				<th>Adresse</th>
				<th>Téléphone</th>
				</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->E_mail);?></td>
				<td><?php echo $this->escape($this->afficher_demande_affiliation->Adresse);?></td>
				<td><?php echo $this->escape("0".$this->afficher_demande_affiliation->Telephone);?></td>
				
			</tr>
		</tbody>
	</table>
	
	<script type="text/javascript"> 
		$(function () {
			tableToGrid("#listedemandes_affiliation_1", {height:"auto", caption: "Informations sur l'entreprise"});
			tableToGrid("#listedemandes_affiliation_2", {height:"auto", caption: "Coordonnées de l'entreprise"});
		});
	</script>
	
	<?php 
	
	$auth=Zend_Auth::getInstance();
	$profil = $auth->getIdentity();   
	$droits = $profil->Droits;

	if(($droits == 3) && (!isset($this->entrepriseExiste->Nom_entreprise)))
		{
			//lien pour creer l'entreprise
			echo "<br /><a href='".$this->url(array('controller'=>'Entreprise',
													'action'=>'ajouter-entreprise', 
													'Num_siret'=>($this->afficher_demande_affiliation->Num_siret), 
													'Nom_entreprise'=>($this->afficher_demande_affiliation->Nom), 
													'Adresse'=>($this->afficher_demande_affiliation->Adresse), 
													'Num_tel'=>($this->afficher_demande_affiliation->Telephone), 
													'Nombre_employes'=>($this->afficher_demande_affiliation->Nombre_employes), 
													'E_mail'=>($this->afficher_demande_affiliation->E_mail)
													))."'>Valider l'affiliation de l'entreprise</a>";
		}
	
	//lister les notes de cette demande et les afficher
	echo $this->action('afficher-notes', 'Note', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 

	//afficher la liste des documents + traiter la DADS
	echo $this->action('afficher-documents', 'Document', null, array('id' => ($this->afficher_demande_affiliation->Id_demande))); 
	if(($droits == 3) && (isset($this->entrepriseExiste->Nom_entreprise)))
		{
			echo "<a href='".$this->url(array('controller'=>'Document','action'=>'traiter-dads', 'id'=>($this->afficher_demande_affiliation->Id_demande), 'id_ent'=>($this->entrepriseExiste->Id_utilisateur)))."'>Traiter le fichier de DADS</a>";
		}
		
	//appel de l'action demande du controller AfficherLesDemandes
	//formulaire pour ajouter une note
	echo $this->action('ajouter-note', 'Note', null, array('id' => ($this->afficher_demande_affiliation->Id_demande), 'prov' => (md5("demandeAffiliation")))); 
	
	//on ajoute un document
	echo $this->action('ajouter-document', 'Document', null, array('id' => ($this->afficher_demande_affiliation->Id_demande), 'prov' => (md5("demandeAffiliation")))); 
	?>
	
</div>



