<?php
	$this->title = 'Notre agence en Ile-de-France';
	$this->headTitle($this->title);
?>

<div id="view-content">
	<div id="box_coordonnees">
		<h3>Agence d'Evry</h3>
		<br>
		<p>223 rue Vinz' Elgayzou<br>91000 EVRY</p>
		<p>Tel. : 01 64 99 47 76<br>Fax : 01 64 99 37 45
		<br>Email : <a href="mailto:domingues.nicolas@gmail.com">contact@crc.fr</a></p>
	</div>
	<div id="map">
		<iframe width="450" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.fr/maps/ms?ie=UTF8&amp;msa=0&amp;msid=210583260585869279565.0004a3750ddcf97a6b2be&amp;ll=48.62396,2.437484&amp;spn=0.007971,0.01929&amp;iwloc=0004a3750ddec45700ec1&amp;output=embed"></iframe><br /><small>Afficher <a href="http://maps.google.fr/maps/ms?ie=UTF8&amp;msa=0&amp;msid=210583260585869279565.0004a3750ddcf97a6b2be&amp;ll=48.62396,2.437484&amp;spn=0.007971,0.01929&amp;iwloc=0004a3750ddec45700ec1&amp;source=embed" style="color:#0000FF;text-align:left">Allée Haute</a> sur une carte plus grande</small>
	</div>
</div>


