<h3>Carrière</h3>
<div id="view-content">

	<table id='carriere' >
		<thead>
			<tr>
				<th>Trimestres Cumulés</th>
				<th>Points cumulés</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->carriere->Trimestre_cumul);?></td>
				<td><?php echo $this->escape($this->carriere->Points_cumul);?></td>
				</tr>
		</tbody>
	</table>
	
	
	<?php
		//On affiche la carrière de l'adhérent
		echo $this->action('afficher-Periode', 'Periode', null, array('id' => ($this->carriere->Id_carriere))); 
	?>
</div>
<script>
		$(function () {
			tableToGrid("#carriere", {height:"auto", caption: "Informations sur la carrière"});
		});
	</script>