<br /><br />
<div id="view-content">
	<p class="news_intro">
		Voici votre plan de départ en retraite :
	</p>
	<p class="news_content">
	Le plan de liquidation de la retraite suivant présente:
	<ul>
		<li>Les 25 meilleurs années donnant droit au versement de la retraite par la Sécurité Sociale</li>
		<li>Le cumul des points ARRCO/AGIRC totalisé donnant droit à la retraite de la CRC</li>
	</ul>
	
	
	</p>
<?php 
	if($this->validAge && $this->validTrim && $this->validDemande){
		//echo print_r($this->annees);
		?>
		<h3>Retraite Sécurité Sociale</h3>
		<table id='listeannee'>
		<thead>
			<tr>
				<th>Annee</th>
				<th>Salaire perçu</th>
			</tr>
		</thead>
		<?php foreach ($this->annees as $key => $value):?>
			<tr>
				<td><?php echo $key;?></td>
				<td><?php echo $value." €";?></td>
			</tr>
		<?php endforeach;?>
		<tbody>
		</tbody>
		</table>
		<h4>Versements</h4>
		Estimation du salaire moyen donnant correspondant au montant de la retraite de la Sécurité Sociale:</br>
		<ul>
			<li>Salaire mensuel brut moyen: <?php echo $this->salaire_moyen." €"?></li>
			<li>Salaire plafonné Sécurité Sociale: <?php echo $this->salaire_plafonne." €"?></li>
		</ul>
		<i>Note: Ces montants sont à titre d'informations et susceptibles d'être réévalués par la Sécurité Sociale</i>
		
		<h3>Retraite CRC</h3>
		<h4>Récapitulatif de votre situation</h4>
		<table id='recap_adherent'>
		<thead>
			<tr>
				<th>Nom</th>
				<th>Prenom</th>
				<th>Date Naissance</th>
				<th>Numéro SS</th>
				<th>Trimestre cumulés</th>
			</tr>
		</thead>
			<tr>
				<td><?php echo $this->escape($this->adherent['Nom'])?></td>
				<td><?php echo $this->escape($this->adherent['Prenom'])?></td>
				<td><?php echo $this->escape($this->adherent['Date_naissance'])?></td>
				<td><?php echo $this->escape($this->adherent['NumSS'])?></td>
				<td><?php echo $this->escape($this->plancarriere['Trimestre_cumul'])?></td>
			</tr>
		<tbody>
		</tbody>
		</table>
		
		<h4>Versements</h4>
		<table id='recap_versements'>
		<thead>
			<tr>
				<th>Type de point</th>
				<th>Nombre de points</th>
				<th>Valeur du point</th>
				<th>Montant</th>
			</tr>
		</thead>
			<tr>
				<td>Point ARRCO</td>
				<td><?php echo $this->escape($this->points_ARRCO)?></td>
				<td><?php echo $this->arrco?></td>
				<td><?php echo round($this->arrco*floatval($this->points_ARRCO),2);?> €</td>
			</tr>
			<tr>
				<td>Point AGIRC</td>
				<td><?php echo $this->escape($this->points_AGIRC)?></td>
				<td><?php echo $this->agirc?></td>
				<td><?php echo round($this->agirc*floatval($this->escape($this->points_AGIRC)),2);?> €</td>
			</tr>
		<tbody>
			<tr>
				<td></td>
				<td></td>
				<td>TOTAL ANNUEL BRUT: </td>
				<td><?php echo round($this->agirc*floatval($this->escape($this->points_AGIRC)),2)+round($this->arrco*floatval($this->points_ARRCO),2);?> €</td>
			</tr>
		
		</tbody>
		</table>
		<?php 
		
		//lister les notes de cette demande et les afficher
		//echo $this->action('afficher-notes', 'Note', null, array('id' => ($this->demande_depart->Id_demande))); 
		
		//formulaire pour ajouter une note
		//echo $this->action('ajouter-note', 'Note', null, array('id' => ($this->demande_depart->Id_demande), 'prov' => (md5("demandeDepart"))));
		$auth=Zend_Auth::getInstance(); 
		$profil = $auth->getIdentity();
		$droits = $profil->Droits;
		if($droits == 3){
			echo "<a href='".$this->url(array('controller'=>'Carriere','action'=>'depart-retraite', 'id'=>($this->Id_utilisateur)))."'>Valider le plan de liquidation de la retraite</a>";
		}
		}else{
		?>
		L'Adhérent n'a pas de droit au départ à la retraite.
		<?php 
		}
		
	?>
</div>
<script type="text/javascript"> 
	$(function () {
		tableToGrid("#listeannee", {height:"auto", width:"650", caption: "Liste des 25 meilleurs salaires annuls bruts"});
		$("#listeannee").jqGrid('gridResize',{minWidth:300,maxWidth:600,minHeight:100, maxHeight:800});
		tableToGrid("#recap_adherent", {height:"auto", width:"650", caption: "Votre carrière"});
		$("#recap_adherent").jqGrid('gridResize',{minWidth:300,maxWidth:600,minHeight:100, maxHeight:800});
		tableToGrid("#recap_versements", {height:"auto", width:"650", caption: "Votre Plan de retraite"});
		$("#recap_versements").jqGrid('gridResize',{minWidth:300,maxWidth:600,minHeight:100, maxHeight:800});
	});
</script>