<h3>Carrière</h3>
<div id="view-content">

	<table id='carriere' >
		<thead>
			<tr>
				<th>Trimestres Cumulés</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->escape($this->carriere->Trimestre_cumul);?></td>
				</tr>
		</tbody>
	</table>
	
	
	<?php
		//On affiche la carrière de l'adhérent
		echo $this->action('afficher-Periode', 'Periode', null, array('id' => ($this->carriere->Id_carriere))); 
	?>
</div>
<script type="text/javascript"> 
		$(function () {
			tableToGrid("#carriere", {height:"auto", width:"650", caption: "Informations sur la carrière"});
			$("#carriere").jqGrid('gridResize',{minWidth:300,maxWidth:600,minHeight:100, maxHeight:800});
		});
		
		$(function () {
			$("#carriere").jqGrid('gridResize',{minWidth:650,maxWidth:1000,minHeight:100, maxHeight:800});
		});
	</script>