<div id="view-profil-content">
	<div id='profilinfos' >
		<div id='profilinfos-content'>
		<h3>Vos informations</h3>
		<?php 
			$this->title = "Mon Profil";
			$this->headTitle($this->title);
			echo $this->form;
			
		?>
		</div>
	
	</div>
	<div id='profildemandes' >demandes
	<?php echo $this->action('index', 'ListeDemandes', null, array('id' => ($this->id))); ?>
	</div>
	<div id='profilcarriere' >carriere</div>
	 <!-- -->
</div>
