<div id="view-profil-content">
	<div id='profilinfos' >
	infos
	<?php 
		$this->title = "Mon Profil";
		$this->headTitle($this->title);
		echo $this->form;
	?>
	
	</div>
	<div id='profildemandes' >demandes</div>
	
	<div id='profilcarriere' >carriere</div>
	 <!-- -->
</div>
<br /><br />
<div id="view-content">
	<p>View script for controller <b>Profil</b> and script/action name <b>index</b></p>
</div>